
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -B verify sonar:sonar -P it
          -Dsonar.projectKey=blue0121_springeasy
          -Dsonar.organization=blue0121
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=$SONAR_TOKEN
      - name: Deploy to Github Packages
        id: deploy
        run: chmod 755 package.sh && ./package.sh $GITHUB_RUN_NUMBER
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Replace version in README.md and push updated
        run: |
          VERSION="${{ steps.deploy.outputs.version }}"
          echo "Updating README.md with version: $VERSION"
          sed -i "s/\${VERSION}/$VERSION/g" README.md
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README.md with version $VERSION"
          git push
